In [12]:
import tensorflow as tf
import numpy as np
a=3
w=tf.Variable([[0.5,1.0]])
x=tf.Variable([[2.0],[1.0]])
y=tf.matmul(w,x)

init_op=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(y.eval())

[[2.]]


In [17]:
tf.zeros([3,4],np.int32)
tensor=tf.constant(-1.0,shape=[2,3])
tf.zeros_like(tensor)
tf.ones([2,3],np.int32)
tf.ones_like(tensor)
tf.linspace(10.0,12.0,3,name="linspace")
start=3;limit=18;delta=3
tf.range(start,limit,delta)

<tf.Tensor 'range:0' shape=(5,) dtype=int32>

In [19]:
norm=tf.random_normal([2,3],mean=-1,stddev=4)
c=tf.constant([[1,2],[3,4],[5,6]])
shuff=tf.random_shuffle(c)
sess=tf.Session()
print(sess.run(norm))
print(sess.run(shuff))

[[-3.2618136   4.837744   -8.437871  ]
 [-0.76553464 -3.3965816   4.256443  ]]
[[5 6]
 [1 2]
 [3 4]]


In [21]:
state=tf.Variable(0)
new_value=tf.add(state,tf.constant(1))
update=tf.assign(state,new_value)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [34]:
w=tf.Variable([[0.5,1.0]])
x=tf.Variable([[2.0],[1.0]])
y=tf.matmul(w,x)
init_op=tf.global_variables_initializer()
saver=tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
    save_path=saver.save(sess,"./ML")
    print("Model saved in file:" ,save_path)

Model saved in file: ./ML


In [36]:
a=np.zeros((3,3))
ta=tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
input1=tf.placeholder(tf.float32)
input2=tf.placeholder(tf.float32)
output=tf.multiply(input1,input2)
with tf.Session() as sess:
    print(sess.run([output],feed_dict={input1:[7.],input2:[2.]}))

[array([14.], dtype=float32)]
